services:
  portfolio:
    build: .
    container_name: portfolio-next-1
    ports:
      - 3002:3000
    restart: unless-stopped
    networks:
      - dain_cafe

networks:
  dain_cafe:
    external: true
